### ISSUE TITLE
Templates rely in trans filter but not dependency missing in composer.json

### ISSUE THREAD

**Issue by gorkalaucirica** [BenGorUser/TwigBridge#1]
We should add `symfony/twig-bridge` as a dependency? Or decouple from translation component?

**Comment by benatespina** [comment]
The first option, the first option! ;)

**Comment by harikt** [comment]
Here is my thought after #2 . We need to add `symfony/translation` as required in the composer.json if we add `symfony/twig-bridge` for translation component is an optional dependency marked in `symfony/twig-bridge`.

**Comment by benatespina** [comment]
@harikt Yeah! You're right. Can you make PR adding translation component as required dependency, please ?? :)

**Comment by harikt** [comment]
@benatespina send the PR :) .
